Numpy
Hanterar bl.a. arrayer:
Statically typed, mycket snabbare
Arrayer kan endast vara av en datatyp
Cant append or remove elements
supports vector operations

In [2]:
import numpy as np

a = np.array([5, 3, 4, 1, 1])
print(f'{a.dtype = }')
b = np.array([5, 3, 4, 1, 1], dtype=float)

a.dtype = dtype('int32')


In [7]:
c = np.random.random(5) # 0-1
print(c)
d = np.random.randint(10, 20, 3)
print(d)
e = np.zeros(10)
print(e)
f = np.ones(10)
print(f)

[0.74933312 0.34587232 0.34530492 0.66454662 0.36991568]
[11 18 14]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
g = np.linspace(0, 10, 100) # evenly spaced
g
h = np.arange(1, 10, 0.1)
h

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [ ]:
# vectorized operations

In [11]:
a1 = np.array([5, 3, 4, 1, 1])
print(a1 * 2)
print(1 / a1)

[10  6  8  2  2]
[0.2        0.33333333 0.25       1.         1.        ]


In [13]:
a2 = np.array([5, 3, 4])
a3 = np.array([1, 1, 6])

a2 + a3

a2.shape

(3,)

In [ ]:
# indexing and slicing works just like we are used to from python lists. we can also use a list with indexs
# boolean masks/boolean indexing can be use used to filter data in arrays
# boolean masks can be created when useing comparison operators on numpy arrays

In [16]:
a1 = np.array([5, 3, 4, 1, 1])
a1[0]
a1[:3]
a1[[0, 3, 0, 4]] # lista med indexs

array([5, 1, 5, 1])

In [18]:
a2 = np.array([5, 3, 4, 1, 1])

a2[[True, False, False, True, True]] # ska plocka ut alla som är true
a2

array([5, 3, 4, 1, 1])

In [2]:
import numpy as np

a3 = np.array([5, 3, 4, 1, 1])
a3 == 1
a3

array([5, 3, 4, 1, 1])

In [4]:
a4 = np.array([5, 3, 4, 1, 1])
a4 > 3
a4

array([5, 3, 4, 1, 1])

aggregeringsmetoder

In [11]:
a5 = np.array([5, 3, 4, 1, 1])

#np.sum(a5)
print(a5.sum())
print(a5.min())
print(a5.max())
print(a5.mean())


14
1
5
2.8


multidimensional arrays

In [ ]:
array_1d = np.array([5, 3, 4, 1, 1])
array_2d = np.array([5, 3, 4, 1, 1][6, 1, 9, 3, 5])


In [12]:
random_2d = np.random.randint(0, 10, [5, 4])
random_2d

array([[5, 0, 3, 0],
       [4, 5, 3, 4],
       [1, 7, 1, 4],
       [5, 8, 7, 4],
       [6, 1, 2, 1]])

In [13]:
random_3d = np.random.randint(0, 10, [2, 5, 4])
random_3d

array([[[9, 9, 4, 7],
        [4, 7, 5, 8],
        [2, 1, 4, 3],
        [4, 9, 0, 2],
        [1, 8, 7, 9]],

       [[0, 9, 9, 4],
        [1, 8, 1, 8],
        [7, 6, 8, 1],
        [5, 6, 8, 9],
        [2, 1, 5, 1]]])

In [15]:
random_2d[1, 3] # x, y
random_2d[0, :3]

array([5, 0, 3])

In [ ]:
random_2d[]